import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  templateUrl: './input-button-unit.component.html',
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {

  title: string = 'Test';

  @Output() submit: EventEmitter<string> = new EventEmitter(); // this.submit.emit -> emits to parent

  constructor() {
    this.submitTitle('Title');
  }

  ngOnInit() {
  }

  submitTitle(newTitle: string) {
    this.submit.emit(newTitle);
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

}
